name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master

      # prql-compiler
      - run: brew install prql/prql/prql-compiler
      - run: echo "from employees | filter has_dog" | prqlc compile
      # prql-query
      # TODO: move into the prql-query formula
      - uses: egor-tensin/setup-clang@v1
        if: matrix.os == 'ubuntu-latest'

      # TODO: hack — currently this is failing on Linux — https://github.com/prql/homebrew-prql/issues/8
      - run: brew install prql/prql/prql-query
        if: matrix.os != 'ubuntu-latest'
      - run: pq --help
        if: matrix.os != 'ubuntu-latest'

      - run: brew audit --strict --online --git --token-conflicts --tap prql/prql
        
