name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      # prql-compiler
      - run: brew install prql/prql/prql-compiler
      - run: echo "from employees | filter has_dog" | prql-compiler compile
      # prql-query
      # TODO: move into the prql-query formula
      - uses: egor-tensin/setup-clang@v1
        if: matrix.os == 'ubuntu-latest'
      - run: brew install prql/prql/prql-query
      - run: pq --help
