name: update-brew
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
      URL:
        description: 'URL to the .tar of the release'
        required: true
        
jobs:
  editTag:
      runs-on: ubuntu-latest
      outputs:
        tag: ${{ steps.step1.outputs.tag }}
        URL: ${{ steps.step1.outputs.url }}
      steps:
       - run: | 
          export TAG="${{ github.event.inputs.version }}"
          echo $TAG
          export TAG=${TAG#*refs/tags/}
          export TAG=\"${TAG}\"
          echo $TAG
          echo "::set-output name=tag::$TAG"

          export URL=${{ github.event.inputs.URL }}
          export URL=\"${URL}\"
          echo $URL
          echo "::set-output name=url::$URL"

  commitTags:
      needs: editTag
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo ${{needs.editTag.outputs.tag}} ${{needs.editTag.outputs.URL}} 

