name: update-brew
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
      URL:
        description: 'URL to the .tar of the release'
        required: true
        
jobs:
  editTag:
      runs-on: ubuntu-latest
      steps:
       - run: | 
          export TAG="${{ github.event.inputs.version }}"
          echo $TAG
          export TAG=${TAG#*refs/tags/}
          export TAG=\"${TAG}\"
          echo $TAG
          export URL=${{ github.event.inputs.URL }}
          echo $URL
