name: update-brew
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
      URL:
        description: 'URL to the .tar of the release'
        required: true
        
jobs:
  editTag:
      runs-on: ubuntu-latest
      steps:
       - run: | 
          export TAG="${{ github.event.inputs.version }}"
          echo $TAG
          echo ::set-output name=tag::$TAG

  editFormula:
      runs-on: ubuntu-latest
      steps:
       - run: |
          echo $TAG
          echo ${{ steps.var.outputs.tag }}
          echo ${{ github.events.inputs.URL }}
