name: update-brew
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
      URL:
        description: 'URL to the .tar of the release'
        required: true
        
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "the dispatch is working on a new release. version: ${{ github.event.inputs.version }}, and URL: ${{ github.event.inputs.URL }}"
  
  editTag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: edit variable
        run: | 
          echo "TAG=${github.event.inputs.version}" >> $GITHUB_ENV
      - name: test
        run: |
          echo $TAG
          echo ${{ env.TAG }}
