name: update-brew
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
      URL:
        description: 'URL to the .tar of the release'
        required: true
        
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "the dispatch is working on a new release. version: ${{ github.event.inputs.version }}, and URL: ${{ github.event.inputs.URL }}"
  
  editTag:
    runs-on: ubuntu-latest
    steps:
    - run: | 
        echo TAG="${{ github.event.inputs.version }}"\ echo $TAG
        echo "echo $TAG"
        echo "echo TAG"