name: update-brew
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
      URL:
        description: 'URL to the .tar of the release'
        required: true
        
jobs:
  editTag:
      runs-on: ubuntu-latest
      outputs:
        tag: ${{ steps.tagstep.outputs.tag }}
        url: ${{ steps.urlstep.outputs.url }}
      steps:
       - id: tagstep
         run: | 
          export TAG=${{ github.event.inputs.version }}
          echo $TAG
          export TAG=${TAG#*refs/tags/}
          export TAG=\"${TAG}\"
          echo $TAG
          echo "::set-output name=tag::$TAG"

       - id: urlstep
         run: |
          export URL=${{ github.event.inputs.URL }}
          export URL=\"${URL}\"
          echo $URL
          echo "::set-output name=url::$URL"

  commitTags:
      needs: editTag
      runs-on: ubuntu-latest
      steps:
        - run: |
            export TAG=${{ needs.editTag.outputs.tag }}
            export TAG=\"${TAG}\"
            echo $TAG
            export URL=${{ needs.editTag.outputs.url }} 
            export URL=\"${URL}\"
            echo $URL
            

