name: update-brew
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release'
        required: true
      URL:
        description: 'URL to the .tar of the release'
        required: true
        
jobs:
  editTag:
      runs-on: ubuntu-latest
      outputs:
        tag: ${{ steps.tagstep.outputs.tag }}
        url: ${{ steps.urlstep.outputs.url }}

      steps:
       - id: tagstep
         run: | 
          export TAG=${{ github.event.inputs.version }}
          export TAG=${TAG#*refs/tags/}
          echo $TAG
          echo "::set-output name=tag::$TAG"

       - id: urlstep
         run: |
          export URL=${{ github.event.inputs.URL }}
          echo $URL
          echo "::set-output name=url::$URL"

  commitTags:
      needs: editTag
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: changes on prql.rb
          run: |
            export TAG=${{ needs.editTag.outputs.tag }}
            export TAG=\"${TAG}\"
            echo $TAG

            export URL=${{ needs.editTag.outputs.url }} 
            export URL=\"${URL}\"
            echo $URL

            cd Formula
            sed -i "6 s/version .*/version $TAG/" "prql.rb"
            sed -i "4 s/url .*/url $URL/" "prql.rb"

            git config user.name github-actions
            git config user.email github-actions@github.com

            git add .
            git commit -m "Automated update of tag and version"
            git push

            
            
            




            

